In [1]:
import numpy as np

Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента. 

In [45]:
a = np.array([1, 2, 3, 3, 1]).reshape(5, 1)
b = np.array([ 6, 8, 11, 10, 7]).reshape(5,1)
a = np.concatenate((a, b), axis = 1)
mean_a = np.mean(a, axis = 0)
a, mean_a

(array([[ 1,  6],
        [ 2,  8],
        [ 3, 11],
        [ 3, 10],
        [ 1,  7]]),
 array([2. , 8.4]))

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [28]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [37]:
a_centered_sp = a_centered[0,:] @ a_centered[1,:]
print(a_centered_sp / (len(a) - 1))

0.24000000000000024


In [43]:
a_cov = np.cov(a.T)
a.T, a_cov

(array([[ 1,  2,  3,  3,  1],
        [ 6,  8, 11, 10,  7]]),
 array([[1. , 2. ],
        [2. , 4.3]]))

In [46]:
import pandas as pd

Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные: 
[1, 1, 1, 2, 2, 3, 3], 
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].


In [54]:
authors = pd.DataFrame({'author_id':[1,2,3], 'Author_name':['Тургенев', 'Чехов', 'Островский']})
books = pd.DataFrame({'author_id' : [1, 1, 1, 2, 2, 3, 3], 'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 'price': [450, 300, 350, 500, 450, 370, 290]}  )


Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id

In [55]:
authors_price = pd.merge(authors, books, on = 'author_id', how = 'inner')
authors_price

author_id Author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [68]:
top5 = authors_price.sort_values(by = "price", ascending = False ).head(5)
top5

author_id Author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора,минимальная, максимальная и средняя цена на книги этого автора.


In [99]:
authors_stat = authors_price.groupby(['Author_name']).agg(['min','max','mean'])

authors_stat.drop('author_id', axis = 1)



price                 
              min  max        mean
Author_name                       
Островский    290  370  330.000000
Тургенев      300  450  366.666667
Чехов         450  500  475.000000

Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].
Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.
Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.
///

In [101]:
authors_price['cover']=['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id Author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [104]:
book_info = pd.pivot_table(authors_price, columns = 'cover', index = 'Author_name', values = 'price', aggfunc = sum   )
book_info

cover        мягкая  твердая
Author_name                 
Островский    660.0      NaN
Тургенев      650.0    450.0
Чехов           NaN    950.0

In [108]:
book_info.fillna(0)

cover        мягкая  твердая
Author_name                 
Островский    660.0      0.0
Тургенев      650.0    450.0
Чехов           0.0    950.0

In [116]:
pd.to_pickle(book_info, ".\book_info.pkl")

In [122]:
book_info2 = pd.read_pickle(".\book_info.pkl")

In [123]:
book_info2

cover        мягкая  твердая
Author_name                 
Островский    660.0      NaN
Тургенев      650.0    450.0
Чехов           NaN    950.0